# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .
        continue-on-error: true
      - name: Test with pytest
        run: |
          pip install -r requirements-dev.txt;
          pytest tests/test_db/test_crud.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_fetch/test_api.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_fetch/test_cache.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_fetch/test_id_correction.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_fetch/test_parse_data.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_fetch/test_lookup.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_admin/test_admin.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_version/test_version.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_permissions/test_viewer.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_permissions/test_editor.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_permissions/test_admin.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_permissions/test_session.py --doctest-modules --junitxml=junit/test-results.xml
          pytest tests/test_permissions/test_get_permisssion.py --doctest-modules --junitxml=junit/test-results.xml
